# nixpacks.toml

# Specify the providers (languages/runtimes) to use
providers = ["php"]

# Setup phase: Install PHP and any required extensions
[phases.setup]
nixPkgs = ["php", "php83Extensions.curl"]  # php83Extensions.curl is needed for making HTTP requests to FileMaker

# Build phase: No build steps needed for this simple script
[phases.build]
cmds = []

# Start phase: Use the command from your Procfile
[phases.start]
cmd = "php -S 0.0.0.0:$PORT twilio_webhook.php"
